name: pokedex

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6  # Para hacer llamadas a la API
  shared_preferences: ^2.2.2  # Para almacenar favoritos localmente
  flutter_local_notifications: 16.2.0  # Prueba con una versión estable anterior


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/pokeball.png
  uses-material-design: true

